name: Build ZMK 6x15 firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository ทั้งหมด
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. ติดตั้ง Python และ west
      - name: Install Python and West
        run: |
          python3 -m pip install --upgrade pip
          pip install west

      # 3. Initialize ZMK workspace
      - name: Initialize ZMK workspace
        run: |
          cd zmk
          west init -l .
          west update
          west zephyr-export

      # 4. Build firmware
      - name: Build firmware
        run: |
          cd zmk/app
          west build -b nice_nano_v2 \
            -d ../../build/my_6x15 -- \
            -DSHIELD=my_6x15 \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      # 5. Upload firmware artifact
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_6x15_firmware
          path: build/my_6x15/zephyr/zmk.uf2