name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize workspace
        run: west init -l app

      - name: Update modules
        run: west update --fetch-opt=--filter=tree:0

      - name: Export Zephyr CMake package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=my_6x15

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_6x15_firmware
          path: build/zephyr/zmk.uf2